export const PROJECTS = [
    {
      title: 'E-Commerce Platform',
      description: 'A full-stack online shopping platform with user authentication, product management, shopping cart functionality, and payment integration using Stripe API.',
      image: 'https://images.unsplash.com/photo-1637937459053-c788742455be?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3ZWIlMjBkZXZlbG9wbWVudCUyMGNvZGUlMjBzY3JlZW58ZW58MXx8fHwxNzcwMjUzMzg4fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
      tags: ['React', 'Node.js', 'MongoDB', 'Stripe'],
      category: 'Full Stack',
      github: 'https://github.com',
      demo: 'https://example.com',
    },
    {
      title: 'Task Management App',
      description: 'A collaborative task management tool with real-time updates, drag-and-drop functionality, team features, and deadline notifications.',
      image: 'https://images.unsplash.com/photo-1758874384597-92297e5423ae?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2JpbGUlMjBhcHAlMjBkZXZlbG9wbWVudCUyMHdvcmtzcGFjZXxlbnwxfHx8fDE3NzAzNTUyOTB8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
      tags: ['TypeScript', 'React', 'Firebase', 'Tailwind'],
      category: 'Frontend',
      github: 'https://github.com',
      demo: 'https://example.com',
    },
    {
      title: 'Weather Dashboard',
      description: 'An interactive weather application that displays current conditions, 7-day forecasts, and historical data using real-time weather APIs with beautiful data visualizations.',
      image: 'https://images.unsplash.com/photo-1582138825658-fb952c08b282?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9ncmFtbWVyJTIwY29kaW5nJTIwbGFwdG9wJTIwZGVza3xlbnwxfHx8fDE3NzAzNTUyODl8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
      tags: ['React', 'API Integration', 'Charts', 'CSS'],
      category: 'Frontend',
      github: 'https://github.com',
      demo: 'https://example.com',
    },
    {
      title: 'Social Media API',
      description: 'RESTful API for a social media platform with user authentication, post creation, comments, likes, and follow system built with Node.js and Express.',
      image: 'https://images.unsplash.com/photo-1637937459053-c788742455be?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3ZWIlMjBkZXZlbG9wbWVudCUyMGNvZGUlMjBzY3JlZW58ZW58MXx8fHwxNzcwMjUzMzg4fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
      tags: ['Node.js', 'Express', 'PostgreSQL', 'JWT'],
      category: 'Backend',
      github: 'https://github.com',
      demo: 'https://example.com',
    },
    {
      title: 'Portfolio Generator',
      description: 'A Next.js application that allows users to create and customize their portfolio websites with templates, drag-and-drop interface, and export functionality.',
      image: 'https://images.unsplash.com/photo-1758874384597-92297e5423ae?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2JpbGUlMjBhcHAlMjBkZXZlbG9wbWVudCUyMHdvcmtzcGFjZXxlbnwxfHx8fDE3NzAzNTUyOTB8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
      tags: ['Next.js', 'TypeScript', 'Tailwind', 'React DnD'],
      category: 'Full Stack',
      github: 'https://github.com',
      demo: 'https://example.com',
    },
    {
      title: 'Blog Platform',
      description: 'A modern blogging platform with markdown support, SEO optimization, commenting system, and admin dashboard for content management.',
      image: 'https://images.unsplash.com/photo-1582138825658-fb952c08b282?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9ncmFtbWVyJTIwY29kaW5nJTIwbGFwdG9wJTIwZGVza3xlbnwxfHx8fDE3NzAzNTUyODl8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
      tags: ['React', 'Node.js', 'MongoDB', 'Markdown'],
      category: 'Full Stack',
      github: 'https://github.com',
      demo: 'https://example.com',
    },
];