export const PROJECTS = [
    {
      title: 'Technoplay Minishop Platform',
      description: '',
      image: '/images/tech.png',
      tags: ['React', 'Node.js', 'Neon', 'PostgreSQL'],
      category: 'Backend',
      github: 'https://github.com/MrBrightside33/TechnoPlay-MiniShop',
      demo: 'https://techno-play-mini-shop-rico.vercel.app/login',
    },
    {
      title: 'Team Portfolio',
      description: '',
      image: '/images/mc.png',
      tags: ['HTML', 'CSS'],
      category: 'Frontend',
      github: 'https://github.com/MrBrightside33/Team-Mclovin-html-css-',
      demo: 'https://teammclovin.vercel.app/',
    },
    {
      title: 'Personal Portfolio',
      description: '',
      image: '/images/port.png',
      tags: ['HTML', 'CSS'],
      category: 'Frontend',
      github: 'https://github.com/MrBrightside33/Portfolio-html-css-',
      demo: 'https://portfolio-html-css-blush-mu.vercel.app/',
    },
    {
      title: 'Quickfix Home Service Platform',
      description: '',
      image: '/images/qui.png',
      tags: ['HTML', 'CSS',],
      category: 'Frontend',
      github: 'https://github.com/MrBrightside33/QuickFix-html-css-',
      demo: 'https://quick-fix-html-css.vercel.app/',
    },
    {
      title: 'Project',
      description: '',
      image: '/images/code.jpg',
      tags: ['None',],
      category: 'None',
      github: 'https://github.com',
      demo: 'https://example.com',
    },
];